ScienceOlympics/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls import url




urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('science_olympiad.urls')),
    path('', include(('science_olympiad.urls', 'science_olympiad'), namespace="science_olympiad")),
    # path('/', include('science_olympiad.urls', namespace="science_olympiad", app_name="science_olympiad")),
]

science_olympiad/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^form/$', views.view_form, name="view_form"),
    url(r'^(?P<section>\w+)/$', views.view_section, name="view_section"),
    url(r'^inventors/register/$', views.add_inventor2, name='add_inventor'),
    

    # url(r'^contest/(?P<contest_id>\d+)/begin/$', views.begin_contest, name='begin_contest'),
    #
    url(r'^contest/end/$', views.show_contest_endpage, name='end_contest'),
    url(r'^contest/(?P<contest_id>\d+)/walkthrough/$', views.walkthrough_contest, name='handle_walkthrough'),
    url(r'^contest/walkthrough/1/$', views.walkthrough_contest1, name='walkthrough_contest1'),
    url(r'^contest/test_wheel/$', views.test_wheel, name='test_wheel'),

    #To show the first question of the contest
    url(r'^contest/(?P<contest_id>\d+)/(?P<question_id>\d+)/welcome/$', views.show_contest_welcomepage, name='welcome_contest'),
    url(r'^contest/(?P<contest_id>\d+)/question/(?P<question_id>\d+)/$', views.show_question, name='show_question'),



    url(r'^timer/$', views.timer, name='timer'),
    # url('hackathon/form/$', TemplateView.as_view(template_name='science_olympiad/hackathon_form.html'), name='hackathon_form'),
    # url('gallery/form/$', TemplateView.as_view(template_name='science_olympiad/gallery_form.html'), name='gallery_form'),
]

science_olympiad/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from django.db import models

from multiselectfield import MultiSelectField

invention_categories = (
    ('anm', 'علوم الحيوان'),
    ('bhv', 'العلوم الاجتماعية والسلوكية'),
    ('bch', 'الكيمياء الحيوية'),
    ('bmd', 'العلوم الطبية الحيوية والصحية'),
    ('mde', 'الهندسة الطبية الحيوية'),
    ('cbi', 'الأحياء الخلوية والجزيئية'),
    ('chm', 'الكيمياء'),
    ('bit', 'المعلوماتية الحيوية'),
    ('eco', 'علوم الأرض والبيئة'),
    ('emb', 'الأنظمة المدمجة'),
    ('che', 'الطاقة الكيميائية'),
    ('phe', 'الطاقة الفيزيائية'),
    ('mch', 'الهندسة الميكانيكية'),
    ('ene', 'الهندسة البيئية'),
    ('smt', 'علم المواد'),
    ('mat', 'الرياضيات'),
    ('mbi', 'الأحياء الدقيقة'),
    ('ast', 'الفيزياء والفلك'),
    ('bot', 'علوم النبات'),
    ('rai', 'الربوتات والذكاء الاصطناعي'),
    ('prg', 'الأنظمة البرمجية والبرمجة'),
    ('mob', 'العلوم الطبية الانتقالية'),
    ('oth', 'تصنيف آخر')
)

class Inventor(models.Model):
    ar_name = models.CharField(u"الاسم الثلاثي باللغة العربية", max_length=200)
    en_name = models.CharField(u"الاسم الثلاثي باللغة الإنجليزية", max_length=200)
    job = models.CharField(u"الوظيفة", max_length=200)
    workplace = models.CharField(u"جهة العمل/الدراسة", max_length=200)
    invention_name = models.CharField(u"اسم الاختراع", max_length=600)
    inv_category = MultiSelectField(u'التصنيف (يمكن اختيار أكثر من تصنيف)', choices=invention_categories)
    other_category = models.CharField(u"إذا اخترت 'تصنيف آخر'، اذكره هنا ", max_length=600, blank=True, null=True)
    summary = models.TextField(u"ملخص الاختراع")
    is_prototype = models.BooleanField(u"هل يوجد لديك نموذج أولي؟")
    prototype_file = models.FileField(u"الرجاء إرفاق النموذج الأولي كملف PDF إن وجد", blank=True, null=True)
    submission_date = models.DateTimeField(u'تاريخ التسجيل', auto_now_add=True)

    class Meta:
        verbose_name = u"مخترع"
        verbose_name_plural = u"مخترعين"

    def __unicode__(self):
        return self.invention_name

class Contest(models.Model):
    date = models.DateField(u"تاريخ المسابقة", null=True)
    teams = models.TextField(u'الفِرق المنافِسة', null=True, blank=True)

    class Meta:
        verbose_name = u"مسابقة"
        verbose_name_plural = u"مسابقات"

    def __unicode__(self):
        return 'Contest Number: '+ str(self.pk)

class ContestQuestion(models.Model):
    contest = models.ForeignKey(Contest, verbose_name=u'المسابقة', default="", on_delete=models.CASCADE)
    text = models.TextField(u'نص السؤال')
    category = models.CharField(u'الفئة', max_length=100)
    olympiad_version = models.CharField(u'نسخة الأولمبياد', max_length=100, null=True) #May be used later in life
    is_last_main = models.BooleanField(u'هل هو السؤال الأخير من الأسئلة الأساسية؟', default=False)
    is_extra = models.BooleanField(u'هل السؤال إضافي؟', default=False)

    class Meta:
        verbose_name = u"سؤال"
        verbose_name_plural = u"أسئلة"

    def __unicode__(self):
        return self.text

class ContestAnswer(models.Model):
    question = models.ForeignKey(ContestQuestion, verbose_name=u'السؤال', on_delete=models.CASCADE)
    text = models.TextField(u'نص الجواب')
    is_correct = models.BooleanField(u'هل الجواب صحيح؟', default=False)
    is_excludable = models.BooleanField(u'هل يمكن حذف الجواب؟', default=False)
    letter_choices = (
        ('a', u'أ'),
        ('b', u'ب'),
        ('c', u'ج'),
        ('d', u'د'),
    )
    choice_letter = models.CharField(max_length=1, choices=letter_choices,
                    verbose_name=u"حرف الخيار", default="")

    class Meta:
        verbose_name = u"جواب"
        verbose_name_plural = u"أجوبة"

    def __unicode__(self):
        return self.text

science_olympiad/forms.py
from django.forms import ModelForm
from .models import Inventor

class InventorForm(ModelForm):
    class Meta:
        model = Inventor
        fields = ['ar_name', 'en_name', 'job', 'workplace', 'invention_name',
                  'inv_category', 'other_category', 'summary', 'is_prototype', 'prototype_file']

science_olympiad/views.py
from django.shortcuts import render, get_object_or_404
from .models import Inventor, Contest, ContestQuestion, ContestAnswer
from .forms import InventorForm


def index(request):
    return render(request, 'science_olympiad/index.html')

def view_form(request):
    return render(request, 'science_olympiad/view_form.html')

def view_section(request, section):
    context = {'section' : section}
    return render(request, 'science_olympiad/view_'+section+'.html', context)

def add_inventor(request):
    if request.method == 'POST':
        instance = Inventor()
        form = InventorForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            instance = form.save()
    elif request.method == 'GET':
        form = InventorForm()
    context = {'form': form}
    return render(request, 'science_olympiad/add_inventor.html', context)

def add_inventor2(request):
    if request.method == 'POST':
        instance = Inventor()
        form = InventorForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            instance = form.save()
    elif request.method == 'GET':
        form = InventorForm()
    context = {'form': form}
    return render(request, 'science_olympiad/add_inventor2.html', context)

def add_inventor3(request):
    if request.method == 'POST':
        instance = Inventor()
        form = InventorForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            instance = form.save()
    elif request.method == 'GET':
        form = InventorForm()
    context = {'form': form}
    return render(request, 'science_olympiad/add_inventor3.html', context)

def begin_contest(request, contest_id):
    contest = get_object_or_404(Contest, pk=contest_id)
    questions = ContestQuestion.objects.filter(contest=contest)
    context = {'contest':contest, 'questions':questions}
    return render(request, 'science_olympiad/begin_contest.html', context)

def show_contest_welcomepage(request, contest_id, question_id):
    contest = get_object_or_404(Contest, pk=contest_id)
    questions = ContestQuestion.objects.filter(contest=contest)
    question = questions.get(pk=question_id)
    context = {'contest_id': contest_id, 'question':question,}
    return render(request, 'science_olympiad/show_contest_welcomepage.html', context)

def show_contest_endpage(request):
    return render(request, 'science_olympiad/show_contest_endpage.html')

def walkthrough_contest(request, contest_id):
    contest = get_object_or_404(Contest, pk=contest_id)
    questions = ContestQuestion.objects.filter(contest=contest)
    context = {'contest': contest, 'questions': questions}
    return render(request, 'science_olympiad/walkthrough_contest.html', context)

def handle_walkthrough(request, contest_id):
    contest = Contest.objects.get(pk=contest_id)
    question_pool = ContestQuestion.objects.filter(contest=contest)
    next_question = question_pool.first()
    if next_question:
        choices = []
        for choice in next_question.contestanswer_set.all():
            choice = {'pk': choice.pk,
                      'text': choice.text,}
            choices.append(choice)
        return {"question_text": next_question.text,
                "question_pk": next_question.pk,
                "choices": choices}
    else:
        return {'done': 1}

def walkthrough_contest1(request):
    contest = get_object_or_404(Contest, pk=1)
    questions = ContestQuestion.objects.filter(contest=contest)
    context = {'contest': contest, 'questions': questions}
    return render(request, 'science_olympiad/walkthrough_contest1.html', context)

def test_wheel(request):
    return render(request, 'science_olympiad/test_wheel.html')

# TODO: Fix this whole file
# the actual view for the game that works is show_question()

def show_question(request, contest_id, question_id):
    contest = get_object_or_404(Contest, pk=contest_id)
    questions = ContestQuestion.objects.filter(contest=contest)
    question = questions.get(pk=question_id)
    choices = question.contestanswer_set.all()
    choice1 = choices.get(choice_letter='a')
    choice2 = choices.get(choice_letter='b')
    choice3 = choices.get(choice_letter='c')
    choice4 = choices.get(choice_letter='d')
    for choice in choices:
        if choice.is_correct:
            answer = choice
    excludables = question.contestanswer_set.filter(is_excludable=True)
    # excludable_1 = null
    # excludable_2 = null
    if len(list(excludables)) == 2:
        excludables = list(excludables)
        excludable_1 = excludables.pop()
        excludable_2 = excludables.pop()
    next_question_id = int(question_id) + 1
    context = {'contest': contest, 'questions': questions, 'question':question,
               'choice1':choice1, 'choice2':choice2,
               'choice3':choice3, 'choice4':choice4,
               'next_question_id':next_question_id, 'answer':answer,
               'excludable_1':excludable_1, 'excludable_2':excludable_2}
    return render(request, 'science_olympiad/show_question.html', context)

def timer(request):
    return render(request, 'science_olympiad/timer.html')

science_olympiad/templates/science_olympiad/add_inventor.html
<!--
 =========================================================
 * Material Kit - v2.0.6
 =========================================================

 * Product Page: https://www.creative-tim.com/product/material-kit
 * Copyright 2019 Creative Tim (http://www.creative-tim.com)
   Licensed under MIT (https://github.com/creativetimofficial/material-kit/blob/master/LICENSE.md)


 =========================================================

 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. -->

{% extends 'science_olympiad/base.html' %}{% load static %}

{% block title %}تسجيل المخترعين{% endblock %}

{% block style %}

#form{
  margin:100px
};

@media only screen and (max-width: 991px) {
  #form {
    margin:0px;
    width:100%;
    padding-top:100px;
  }
}
{% endblock %}

{% block content %}
   <div class="page-header header-filter" style="background-image:url({% static 'science_olympiad/images/header.jpg' %}) ; background-size: cover; background-position: top center;">
    <div class="container">
      <div class="row">
      <div class="col-lg-12">
        <div id="terms" class="card card-login" style="border:200px;">
        <p align="right" style="padding-right:15px; padding-top:20px">ضوابط التسجيل:</p>
        <ol style="text-align:right">
          <li>أن يكون المشارك/المشاركة سعودي الجنسية.</li>
          <li>أن يكون عمر المشارك/المشاركة ١٨ سنة فما فوق.</li>
          <li>الحضور الشخصي للمشارك/المشاركة لكافة أيام المعرض.</li>
          <li>لإدارة المسابقة الحق في استبعاد أي مشارك إذا ثبت إدخال أية معلومات غير صحيحة.</li>
        </ol>
        <p align="right" style="padding-right:15px; padding-top:20px">شروط المشاركة بالابتكار:</p>
        <ol style="text-align:right">
          <li>أن يكون التسجيل بالابتكار فردي، ولن يسمح بالمشاريع الجماعية.</li>
          <li> يشترط أن يحتوي ملخص المشروع على حل مشكلة و أهداف الابتكار، الأصالة، والتنفيذ.</li>
          <li>يحق لإدارة المسابقة استبعاد المشاريع التي لا تتوفر فيها معلومات علمية أساسية في ملخص المشروع.</li>
          <li>أن يكون العمل ذو أصالة ومن ابتكار المشارك/المشاركة.</li>
          <li>أن تكون المشاركة ضمن مجالات المسابقة المذكورة أدناه.</li>
          <li>استيفاء العمل لكافة شروط الأخلاقيات العلمية ومعايير الأمن والسلامة المعمول بها في المملكة العربية السعودية.</li>
          <li>في حال وجود نموذج للابتكار يرجى إحضاره بشرط الالتزام بالقياسات المحددة: (الطول ٥٠سم، العرض ٤٠سم، الارتفاع ٢٠سم)، ولن يُسمح بعرض أكبر من تلك القياسات، ويمكن الاستعانة بعرض مقطع فيديو للنموذج.</li>
          <li>يتطلب إعداد لوحة عرض (بوستر) لعرض الابتكار في المعرض.</li>
        </ol>
        <p align="right" style="padding-right:15px; padding-top:20px">في حال وجود أية أسئلة يرجى التواصل عبر: so.ksauhs@gmail.com</p>
      </div>
      </div>
      </div>
      <div class="row">
      <button id="button" class="btn btn-raised">لقد قمت بقراءة شروط التسجيل و أوافق عليها</button>
      </div>





    </div>
   </div>


      <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 ml-auto mr-auto">
          <div class="card card-login" align="right">
            <form id="form" class="form" method="post" action="">
                <!--<ul>{{form.as_p}}</ul>-->


            <div class="card-header card-header-primary text-center">
            <h4 class="card-title">تسجيل المخترعين في معرض الدَيْجُور 💡</h4>
            </div>

            <div class="card-body">
                {% for field in form %}
                <div class="input-group">
                  <div class="input-group-prepend" style="padding-left:10px; padding-rightt:10px">
                    {% if field.name == 'ar_name' %}
                    الاسم الثلاثي باللغة العربية:
                  </div>
                  <input type="text" class="form-control">
                    {% elif field.name == 'en_name' %}
                    الاسم الثلاثي باللغة الإنجليزية:
                  </div>
                  <input type="text" class="form-control">
                    {% elif field.name == 'job' %}
                    الوظيفة:
                  </div>
                  <input type="text" class="form-control">
                    {% elif field.name == 'workplace' %}
                    جهة العمل/الدراسة:
                  </div>
                  <input type="text" class="form-control">
                    {% elif field.name == 'invention_name' %}
                    اسم الاختراع:
                  </div>
                  <input type="text" class="form-control">
                    {% elif field.name == 'inv_category' %}
                    <div class="row" align="right">
                    التصنيف (يمكن اختيار أكثر من تصنيف):
                    <div class="col-lg-12">
                    {% for x,y in form.fields.inv_category.choices %}
                        <div class="form-check">
                            <label class="form-check-label">
                              <input class="form-check-input" type="checkbox" value=""> {{y}}
                              <span class="form-check-sign">
                                <span class="check"></span>
                              </span>
                            </label>
                          </div>
                    {% endfor %}
                    </div></div>
                    {% elif field.name == 'other_category' %}
                    إذا اخترت 'تصنيف آخر'، اذكره هنا:
                    </div>
                    <input type="text" class="form-control">
                    {% elif field.name == 'summary' %}
                    ملخص الاختراع:
                    </div>
                    <input type="text" class="form-control">
                    {% elif field.name == 'is_prototype' %}
                    هل يوجد لديك نموذج أولي؟
                    </div>
                    <input type="text" class="form-control">
                    {% elif field.name == 'prototype_file' %}
                    الرجاء إرفاق النموذج الأولي كملف PDF إن وجد:
                    </div>
                    <input type="file" class="form-control">
                    {% endif %}
                    </div>
                    {% endfor %}

            </div>
          </form>
        </div>
        </div>
    </div>
</div>

















{% endblock %}

{% block customscript %}
<script type="text/javascript">
$("#form").hide();
$("#button").click(function(){
    $("#button").hide();
    $("#form").show();
    });
</script>
{% endblock %}

science_olympiad/templates/science_olympiad/view_contest.html
<!--
 =========================================================
 * Material Kit - v2.0.6
 =========================================================

 * Product Page: https://www.creative-tim.com/product/material-kit
 * Copyright 2019 Creative Tim (http://www.creative-tim.com)
   Licensed under MIT (https://github.com/creativetimofficial/material-kit/blob/master/LICENSE.md)


 =========================================================

 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. -->

{% extends 'science_olympiad/base.html' %}{% load static %}

{% block title %}المسابقة العلمية{% endblock %}

{% block style %}
.header-filter::before {
    background: rgba(0, 0, 0, 0);
}

.profile-page .profile img{
  max-width: 200px;
}

{% endblock %}

{% block content %}
<div class="profile-page sidebar-collapse">
  <div class="page-header header-filter" data-parallax="true" style="background-image: url({% static 'science_olympiad/images/header.jpg' %});">
       <!------------------------Navbar Start------------------>
          <nav style="height:100px" class="navbar navbar-transparent navbar-expand-lg" id="sectionsNav">

          <div class="container">
            <div  class="navbar-translate">
              <a class="navbar-brand" href="{% url 'science_olympiad:index'%}">
                  <img id="logo" height="130px" style="margin-bottom:0px; margin-top:-100px; margin-right:0px"
                       src="{% static 'science_olympiad/images/logo_white.png' %}">
              </a>
            </div>
          </div>
          </nav>
          <!----------------------Navbar End---------------->
  </div>
  <div class="main ">
    <div class="profile-content">
      <div class="container">
        <div class="row">
          <div class="col-md-6 ml-auto mr-auto">
            <div class="profile">
              <div class="avatar">
                  <img style="background-color:#fff; padding:15px" src="{% static 'science_olympiad/images/sections/black/contest_black.png' %}" class="rounded-circle img-fluid">
              </div>
              <div class="name">
                <h3 class="title">المسابقة العلمية</h3>
              </div>
            </div>
          </div>
        </div>
          <div style="padding-bottom:100px" class="description text-center">

        <div class="row" style="text-align:justify; text-align-last: center">
            هي مسابقة علمية ثقافية وتنافسية تنص على رؤية، وقياس المدى العلمي و الثقافي بين طلبة الجامعة من مختلف الكليات، في مختلف العلوم، وتهدف لخلق بيئة تؤمن بالتنافس الودِّي، لتعزز من أهمية اطلاع الفرد على جميع العلوم. حيث يمثل كل كلية فريق مُكون من أربعة طلاب وطالبات.
كوني/كن جزءًا منها!
        </div>
        <div class="section text-center">
        <p style="text-align:center"></p>
        </div>
        </div>
        </div>
        </div>
    </div>
</div>
{% endblock %}

science_olympiad/templates/science_olympiad/view_gallery.html
<!--
 =========================================================
 * Material Kit - v2.0.6
 =========================================================

 * Product Page: https://www.creative-tim.com/product/material-kit
 * Copyright 2019 Creative Tim (http://www.creative-tim.com)
   Licensed under MIT (https://github.com/creativetimofficial/material-kit/blob/master/LICENSE.md)


 =========================================================

 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. -->

{% extends 'science_olympiad/base.html' %}{% load static %}

{% block title %}معرض الدَيْجُور{% endblock %}

{% block style %}
.header-filter::before {
    background: rgba(0, 0, 0, 0);
}

.profile-page .profile img{
  max-width: 200px;
}

{% endblock %}

{% block content %}
<div class="profile-page sidebar-collapse">
  <div class="page-header header-filter" data-parallax="true" style="background-image: url({% static 'science_olympiad/images/header.jpg' %});">
     <!------------------------Navbar Start------------------>
          <nav style="height:100px" class="navbar navbar-transparent navbar-expand-lg" id="sectionsNav">

          <div class="container">
            <div  class="navbar-translate">
              <a class="navbar-brand" href="{% url 'science_olympiad:index'%}">
                  <img id="logo" height="130px" style="margin-bottom:0px; margin-top:-100px; margin-right:0px"
                       src="{% static 'science_olympiad/images/logo_white.png' %}">
              </a>
            </div>
          </div>
          </nav>
          <!----------------------Navbar End---------------->
  </div>
  <div class="main ">
    <div class="profile-content">
      <div class="container">
        <div class="row">
          <div class="col-md-6 ml-auto mr-auto">
            <div class="profile">
              <div class="avatar">
                  <img style="background-color:#fff; padding:15px" src="{% static 'science_olympiad/images/sections/black/lectures_black.png' %}" class="rounded-circle img-fluid">
              </div>
              <div class="name">
                <h3 class="title">معرض الدَيْجُور</h3>
              </div>
            </div>
          </div>
        </div>
          <div style="padding-bottom:100px" class="description text-center">

        <div class="row">
          <div class="col-12">في معرض الدَيجُور، يتم تقديم معنى شغف الإنسان في الصناعة عن طريق عرض تسلسل أفكار الإنسان واختراعاته وتطورها عبر الزمان. ويتم فيه أيضًا إبراز اختراعات شبابنا وشابَّاتنا السعوديون بوجود حاضنات الأعمال؛ لتحقيق فرصة الظهور والدعم لهم.</div>
        </div>

        </div>
        </div>
        </div>
    </div>
</div>
{% endblock %}

science_olympiad/templates/science_olympiad/view_hackathon.html
<!--
 =========================================================
 * Material Kit - v2.0.6
 =========================================================

 * Product Page: https://www.creative-tim.com/product/material-kit
 * Copyright 2019 Creative Tim (http://www.creative-tim.com)
   Licensed under MIT (https://github.com/creativetimofficial/material-kit/blob/master/LICENSE.md)


 =========================================================

 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. -->

{% extends 'science_olympiad/base.html' %}{% load static %}

{% block title %}الهاكاثون التقني{% endblock %}

{% block style %}
.header-filter::before {
    background: rgba(0, 0, 0, 0);
}

.profile-page .profile img{
  max-width: 200px;
}

{% endblock %}

{% block content %}
<div class="profile-page sidebar-collapse">
  <div class="page-header header-filter" data-parallax="true" style="background-image: url({% static 'science_olympiad/images/header.jpg' %});">
    <!------------------------Navbar Start------------------>
          <nav style="height:100px" class="navbar navbar-transparent navbar-expand-lg" id="sectionsNav">

          <div class="container">
            <div  class="navbar-translate">
              <a class="navbar-brand" href="{% url 'science_olympiad:index'%}">
                  <img id="logo" height="130px" style="margin-bottom:0px; margin-top:-100px; margin-right:0px"
                       src="{% static 'science_olympiad/images/logo_white.png' %}">
              </a>
            </div>
          </div>
          </nav>
          <!----------------------Navbar End---------------->
  </div>
  <div class="main ">
    <div class="profile-content">
      <div class="container">
        <div class="row">
          <div class="col-md-6 ml-auto mr-auto">
            <div class="profile">
              <div class="avatar">
                  <img style="background-color:#fff; padding:15px" src="{% static 'science_olympiad/images/sections/black/lectures_black.png' %}" class="rounded-circle img-fluid">
              </div>
              <div class="name">
                <h3 class="title">الهاكاثون التقني</h3>
              </div>
            </div>
          </div>
        </div>
          <div style="padding-bottom:100px" class="description text-center">

        <div class="row" style="padding-top:50px">
          <div class="col-lg-12">ستقام بطولة "FIRST LEGO league "العالمية في شهر مارس ٢٠٢٠ في جامعة الملك سعود بن عبدالعزيز للعلوم الصحية بين طلاب و طالبات من مختلف جامعات الرياض ممثلين لمنشأتهم العلمية ، ستكون البطولة مسبقة بورش عمل تقدم لهم من قبل مختصين في مجال تصميم و برمجة الروبوتات. يهدف التحدي الى قياس كفاءة “تصميم و برمجة” الروبوت والذي سيكون منطلق المفاضلة من فريق لأخر، عن طريق مجموعة من المهام المتسلسلة مع حساب النقاط بعد انجاز كل مهمة استناداً على كفاءة انجاز الروبوت للمهمة الموكلة اليه ، بعد انتهاء التحدي يتم مفاضلة الفرق من خلال مجموع النقاط التي جٌمعت اثناء التحدي ليتوج روبوتاً وفريقه بالفوز بجائزة الهاكاثون المالية في الحفل الختامي للبرنامج.</div>
        <div class="row" style="margin:30px"><div class="col-lg-12">
            <img width="100%" src="{% static 'science_olympiad/images/hackathon/1.jpg' %}">
        </div></div>
        <div class="row" style="margin:30px"><div class="col-lg-12">
            <img width="100%" src="{% static 'science_olympiad/images/hackathon/2.jpg' %}">
        </div></div>
        <div class="row" style="margin:30px"><div class="col-lg-12">
            <img width="100%" src="{% static 'science_olympiad/images/hackathon/3.jpg' %}">
        </div></div>
        <br><br><br><br>
        <!--<a href="" class="btn">للتسجيل في المسابقة</a>-->

        <!--<div class="section text-center">-->
        <!--<p style="text-align:center">للاستفسار أو للتواصل مع القادة: ...</p>-->
        <!--</div>-->

          </div>

        </div>
        </div>
        </div>
    </div>
</div>
{% endblock %}